### Criar uma nova encomenda (POST)
POST http://localhost:3000/Encomenda
Content-Type: application/json

{
  "id": "1",
  "remetente": "João Silva",
  "destinatario": "Maria Oliveira",
  "local_atual": "Centro de Distribuição SP",
  "Previsao_entrega": "2025-02-25"
}

### Buscar todas as encomendas (GET)
GET http://localhost:3000/Encomenda

### Buscar uma encomenda específica pelo ID (GET)
GET http://localhost:3000/Encomenda/1

### Atualizar uma encomenda pelo ID (PUT)
PUT http://localhost:3000/Encomenda/1
Content-Type: application/json

{
  "local_atual": "Centro de Distribuição RJ",
  "status": "Em trânsito"
}

### Excluir uma encomenda pelo ID (DELETE)
DELETE http://localhost:3000/Encomenda/1

### Buscar novamente para verificar se foi excluído (GET)
GET http://localhost:3000/Encomenda/1
