### Criar uma nova encomenda (POST)
POST http://localhost:3001/encomenda
Content-Type: application/json

{
  "id": "2",
  "remetente": "João Silva",
  "destinatario": "Maria Oliveira",
  "local_atual": "Centro de Distribuição SP",
  "previsao_entrega": "2025-02-25"
}

### Buscar todas as encomendas (GET)
GET http://localhost:3001/encomenda
Content-Type: application/json

### Buscar uma encomenda específica pelo ID (GET)
GET http://localhost:3001/encomenda/2
Content-Type: application/json

### Atualizar uma encomenda pelo ID (PUT)
PUT http://localhost:3001/encomenda/3
Content-Type: application/json

{
  "local_atual": "Centro de Distribuição RJ",
  "previsao_entrega": "Encomenda Entregue"
}

### Buscar todas as encomendas (GET)
GET http://localhost:3001/encomenda
Content-Type: application/json


### Excluir uma encomenda pelo ID (DELETE)
DELETE http://localhost:3001/encomenda/7
Content-Type: application/json

### Buscar todas as encomendas (GET)
GET http://localhost:3001/encomenda
Content-Type: application/json


###
